package uk.ac.cam.ch.wwmm.oscar.tools;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Properties;

public abstract class OscarPropertiesIO {

	public static void loadProperties(OscarProperties properties, File propsFile)
	throws FileNotFoundException, IOException {
		Properties props = new Properties();
		props.load(new FileInputStream(propsFile));
		properties.initialiseWithProperties(props);
	}
	
	public static void saveProperties(OscarProperties properties, File propsFile)
	throws FileNotFoundException, IOException {
		Properties props = properties.getProperties();
		storeSorted(props, new FileOutputStream(propsFile), "Autogenerated by Oscar");
	}
		
	private static void storeSorted(Properties props, OutputStream os, String comment) throws IOException {
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		props.store(baos, comment);
		List<String> lines = new ArrayList<String>();
		ByteArrayInputStream bais = new ByteArrayInputStream(baos.toByteArray());
		BufferedReader br = new BufferedReader(new InputStreamReader(bais));
		PrintWriter pw = new PrintWriter(new OutputStreamWriter(os));
		for(String line = br.readLine();line != null;line = br.readLine()) {
			if(line.startsWith("#"))  {
				pw.println(line);
			} else {
				lines.add(line);
			}
		}
		Collections.sort(lines);
		for(String line : lines) {
			pw.println(line);
		}
		pw.flush();
	}

}
